---
- name: create k8s namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1 
      kind: Namespace
      metadata:
        name: ascn-cluster

- name: app ghost service 
  kubernetes.core.k8s:
    state: present
    src: ../ghost-service.yml

- name: app ghost deployment
  kubernetes.core.k8s:
    state: present
    src: ../ghost-deployment.yml

