---
# Playbook to deploy Ghost and its components


- name: Create secret
  hosts: localhost  
  gather_facts: false  
  roles:
    - create_secret
    
- name: Deploy application
  hosts: localhost  
  gather_facts: false  
  roles:
    - mysql    
    - ghost
