apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        env:
        - name: db_client
          value: mysql
        - name: db_host
          value: mysql-service
        - name: db_user
          value: ghostuser
        - name: db_password
          value: "123456"
        - name: db_name
          value: ghost
        - name: url
          value: http://ghost.org
        ports:
        - containerPort: 2368 
          protocol: TCP 
