apiVersion: v1 
kind: Service
metadata:
  name: ghost-service
  labels:
    app: ghost
spec:
  type: LoadBalancer    
  selector:
    app: ghost
  ports:
    - port: 2368 #porta exposta internamente no cluster
      targetPort: 2368 #porta onde os conteiners estão à escuta
      nodePort: 30007
     
