---
# Undeploy dos serviços do ghost

 - name: Undeploy Ghost Services
   command: kubectl delete -l app=ghost-blog pods,services,deployments -n "{{ namespace }}"
   
 - name: Delete Services
   shell: kubectl delete service --all 
   
 - name : Remove user data
   command: kubectl delete -l app=ghost deployments,services,pods -n "{{ namespace }}"
