
- name: Create MySQL Service 
  kubernetes.core.k8s:
    state: present 
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ghost-mysql
        namespace: "{{ namespace }}"
        labels:
          app: ghost
      spec:
        ports:
          - port: "{{ database_port }}"
        selector:
          app: ghost
          tier: mysql


- name: Create persistent volume storage 
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
         name: mysql-pvclaim
         namespace: "{{ namespace }}"
      spec:
         accessModes:
         - ReadWriteOnce
         resources:
           requests:
             storage: 10Gi


- name: Deploy mysql
  kubernetes.core.k8s:
    state: present 
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ghost-mysql
        namespace: "{{ namespace }}"
        labels:
          app: ghost
      spec:
        selector:
          matchLabels:
            app: ghost
            tier: mysql
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: ghost
              tier: mysql
          spec:
            containers:
            - image: mysql:latest
              name: mysql
              env:
              - name: MYSQL_DATABASE
                value: "{{ database }}"
              - name: MYSQL_USER
                value: "{{ database_user }}"
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: ghost-data
                    key: password
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: ghost-data
                    key: root_password
              ports:
              - containerPort: "{{ database_port }}"
                name: mysql
              volumeMounts:
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql
            volumes:
            - name: mysql-persistent-storage
              persistentVolumeClaim:
                claimName: mysql-pvclaim
