---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
       claimName: mysql-pv-claim
  containers:
    - name: pod-demo
      image: nginx
      resources:
        limits:
          cpu: 10m
          memory: 80Mi
        requests:
          cpu: 10m
          memory: 80Mi
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mysql-persistent-storage
      
