- name: Create secret
  kubernetes.core.k8s:
    namespace: "{{ namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ghost-data
      type: Opaque
      data: 
        password: UGFzc3dvcmQkMTIzNDU2  # Password$123456
        root_password: UGFzc3dvcmQkMTIzNDU2  # Password$123456
