- name: create k8s namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1 
      kind: namespace
      metadata:
        name: ascn-cluster

- name: mysql service
  kubernetes.core.k8s:
    state: present
    src: ../mysql-service.yml

- name:  mysql deployment 
  kubernetes.core.k8s:
    state: present
    src: ../mysql-deployment.yml
