apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: ascn-cluster
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        env:
        - name: dbclient
          value: mysql
        - name: dbhost
          value: mysql-service
        - name: dbuser
          value: ghostuser
        - name: dbpassword
          value: pass
        - name: dbname
          value: ghost
        - name: url
          value: http://ghost.org
        ports:
        - containerPort: 2368 
